version: '3.7'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
      POSTGRES_DB: n8ndb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8ndb
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8npass
      N8N_HOST: 0.0.0.0
      N8N_PORT: 5678
      N8N_EDITOR_BASE_URL: https://${CODESPACE_NAME}-80.app.github.dev
      WEBHOOK_URL: https://${CODESPACE_NAME}-80.app.github.dev
      N8N_BASIC_AUTH_ACTIVE: true
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: strongpass123
      N8N_SKIP_ORIGIN_CHECK: true
      N8N_DISABLE_UI_ACCESS_CONTROL: true

    restart: always
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - n8n

volumes:
  postgres_data:
